---
title: "first_model"
author: "Sara Østergaard"
date: "23/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
pacman::p_load(
  tidyverse,
  here,
  posterior,
  cmdstanr,
  brms, 
  boot
)
```

## data
```{r}
df <- read_csv('C:/Users/Sara/Documents/8semester/cognitive_modeling/cognitive_modeling/assignments/a1/RandomAgainstMemory.csv') 

df <- df %>% filter(rate==0.8 & mem_constraint==125 & noise==0)

df %>% group_by(matcher) %>% 
  summarize(n())

```


## random model
```{r}
file <- file.path('random_agent.stan')
mod <- cmdstan_model(file, cpp_options = list(stan_threads=TRUE))
```
```{r}
# data for this model
data <- list(n = nrow(df[1:1000,]), h = df[1:1000,]$mismatcher)

# following command calls stan
samples <- mod$sample(
  data = data,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1000,
  iter_sampling = 2000,
  refresh = 500,
  max_treedepth = 20,
  adapt_delta = 0.99,
)

```

```{r}
# output
samples$summary()
```

## data
```{r}
df <- read_csv('C:/Users/Sara/Documents/8semester/cognitive_modeling/cognitive_modeling/assignments/a1/WSLSAgainstMemory.csv') 

df <- df %>% filter(mem_constraint==125 & noise==0)

round <- c()
for (i in 1:(nrow(df)/max(df$trial))){
  round <- c(round, rep(i, max(df$trial)))
}
df$round <- round

df <- df %>% group_by(round) %>% 
  mutate(
    'prevRate_mismatcher' = cumsum(mismatcher)/seq_along(mismatcher)
  )

df %>% group_by(matcher) %>% 
  summarize(n())

```

## memory model
```{r}
file <- file.path('memory_agent.stan')
mod <- cmdstan_model(file, cpp_options = list(stan_threads=TRUE))
```

```{r}
# data for this model
data <- list(n = nrow(df[1:1000,]), h = df[1:1000,]$matcher, r = df[1:1000,]$prevRate_mismatcher,
             prior_mean_alpha=0, prior_mean_beta=0, prior_sd_alpha=1, prior_sd_beta=0.5)

# following command calls stan
samples <- mod$sample(
  data = data,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1000,
  iter_sampling = 2000,
  refresh = 500,
  max_treedepth = 20,
  adapt_delta = 0.99,
)

```

```{r}
# output
summary <- samples$summary()
summary
```

```{r}
alpha = summary[summary$variable=='alpha',]$mean
beta = summary[summary$variable=='beta',]$mean
inv.logit(alpha + beta*0.5)
```


```{r}
draws_df <- as_draws_df(samples$draws())
```

```{r}
ggplot(draws_df, aes(.iteration, alpha, group=.chain, color=.chain)) + 
  geom_line()+theme_classic()

ggplot(draws_df, aes(.iteration, beta, group=.chain, color=.chain)) + 
  geom_line()+theme_classic()
```


