---
title: "assignment 4"
author: "Sara Østergaard"
date: "21/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
pacman::p_load(
  tidyverse,
  here,
  posterior,
  cmdstanr,
  brms, 
  boot, 
  loo,
  patchwork
)

source('util.R')
```

## Simulate data
```{r}

# parameters
temp <- 0.5 # same for both conditions
alpha_cond1 <- 0.6
alpha_cond2 <- 0.8
p <- 0.75  # probability that choice 1 gives a reward

# define number of trials
n_trials <- 5000

# make sure the dataframe doesn't exist
d <- NULL


# simulate
for (cond in 1:2){
  print(paste("condition = ", cond))
  # simulate bot
  correct_choice <- rbinom(n_trials, 1, p)
  # initialize values for the two choices
  values <- c(0,0)
  # define correct learning rate for the condition
  alpha <- ifelse(cond==1, alpha_cond1, alpha_cond2)
  print(alpha)
  # make tmp dataframe
  tmp <- tibble(
    choice = rep(0, n_trials),
    value1 = rep(0, n_trials),
    value2 = rep(0, n_trials),
    feedback = rep(0, n_trials),
    condition = rep(0, n_trials),
    trial = rep(0, n_trials),
    learning_rate = rep(0, n_trials)
  )
  
  for (trial in 1:n_trials){
    if (trial %% 100 == 0){
     print(paste("trial = ", trial)) 
    }
    
    choice <- rbinom(1, 1, softmax(values[2]-values[1], temp))
    feedback <- ifelse(correct_choice[trial]==choice, 1, -1)
    values <- valueUpdate(values, alpha, choice, feedback)
    
    # fill in dataframe
    tmp$choice[trial] <- choice + 1
    tmp$value1[trial] <- values[1]
    tmp$value2[trial] <- values[2]
    tmp$feedback[trial] <- feedback
    tmp$condition[trial] <- cond
    tmp$trial[trial] <- trial
    tmp$learning_rate[trial] <- alpha
    
  }
  if (exists("d")){
    d <- rbind(d, tmp)
  } else {
    d <- tmp
  }
}


```

```{r}
# save simulated data
# write_csv(d, "simulated_data.csv")
```


## model
```{r}
# read data
d <- read_csv('simulated_data.csv')
```


```{r}
# load model
file <- file.path('reinforcement_learning.stan')
mod <- cmdstan_model(file, cpp_options = list(stan_threads=TRUE))
print("Done compiling!")
```
Prepare data and run model
```{r}
# make data frames to make into matrices
df_cond <- d %>% mutate(cond = condition-1) %>% 
  subset(select=c(cond, condition, trial)) %>% 
  pivot_wider(names_from = condition, values_from = cond)

df_choice <- d %>% subset(select=c(choice, condition, trial)) %>% 
  pivot_wider(names_from = condition, values_from = choice)

df_feedback <- d %>% subset(select=c(feedback, condition, trial)) %>% 
  pivot_wider(names_from = condition, values_from = feedback)

# data for the model
data <- list(
  trials = max(d$trial),
  cond = as.matrix(df_cond[,2:3]),
  choice = as.matrix(df_choice[,2:3]),
  feedback = as.matrix(df_feedback[,2:3]),
  alpha1_prior_values = c(0, .5),
  alpha2_prior_values = c(0, .5),
  temp_prior_values = c(0, 1)
)

# call stan
samples <- mod$sample(
  data = data,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1000,
  iter_sampling = 2000,
  refresh = 1000,
  max_treedepth = 20,
  adapt_delta = 0.99
)

```

```{r}
# samples$summary()

draws_df <- as_draws_df(samples$draws())
```

chains
```{r}
ggplot(draws_df, aes(.iteration, temperature, group = .chain, color = .chain)) +
  geom_line() +
  theme_classic()

ggplot(draws_df, aes(.iteration, alpha1, group = .chain, color = .chain)) +
  geom_line() +
  theme_classic()

ggplot(draws_df, aes(.iteration, alpha2, group = .chain, color = .chain)) +
  geom_line() +
  theme_classic()
```
prior posterior update
```{r}
alpha1_update <- ggplot(draws_df) +
  geom_density(aes(alpha1_transformed), fill='blue', alpha=0.5) + 
  geom_density(aes(alpha1_prior), fill='red', alpha=0.5) + 
  theme_bw()

alpha2_update <- ggplot(draws_df) +
  geom_density(aes(alpha2_transformed), fill='blue', alpha=0.5) + 
  geom_density(aes(alpha2_prior), fill='red', alpha=0.5) + 
  theme_bw()

alpha1_update + alpha2_update
```

```{r}
alpha1_update <- ggplot(draws_df) +
  geom_density(aes(alpha1), fill='blue', alpha=0.5) + 
  geom_density(aes(logit(alpha1_prior)), fill='red', alpha=0.5) + 
  theme_bw()

alpha2_update <- ggplot(draws_df) +
  geom_density(aes(alpha2), fill='blue', alpha=0.5) + 
  geom_density(aes(logit(alpha2_prior)), fill='red', alpha=0.5) + 
  theme_bw()

alpha1_update + alpha2_update
```

```{r}
ggplot(draws_df) +
  geom_density(aes(temperature_transformed), fill='blue', alpha=0.5) + 
  geom_density(aes(temperature_prior), fill='red', alpha=0.5) + 
  theme_bw()
```


## parameter recovery
```{r}
n_trials <- c(100, 500,  1000, 
              1500, 2000, 2500,
              3000, 3500, 4000)

recovery_df <- NULL

for (n_trial in n_trials){
  print(paste('n_trial = ', n_trial))
  tmp_d <- d %>% filter(trial <= n_trial)
  
  # make data frames to make into matrices
  df_cond <- tmp_d %>% mutate(cond = condition-1) %>% 
    subset(select=c(cond, condition, trial)) %>% 
    pivot_wider(names_from = condition, values_from = cond)
  
  df_choice <- tmp_d %>% subset(select=c(choice, condition, trial)) %>% 
    pivot_wider(names_from = condition, values_from = choice)
  
  df_feedback <- tmp_d %>% subset(select=c(feedback, condition, trial)) %>% 
    pivot_wider(names_from = condition, values_from = feedback)
  
  # data for the model
  data <- list(
    trials = max(tmp_d$trial),
    cond = as.matrix(df_cond[,2:3]),
    choice = as.matrix(df_choice[,2:3]),
    feedback = as.matrix(df_feedback[,2:3]),
    alpha1_prior_values = c(0, .5),
    alpha2_prior_values = c(0, .5),
    temp_prior_values = c(0, 1)
  )
  
  # call stan
  samples <- mod$sample(
    data = data,
    seed = 123,
    chains = 2,
    parallel_chains = 2,
    threads_per_chain = 2,
    iter_warmup = 1000,
    iter_sampling = 2000,
    refresh = 1000,
    max_treedepth = 20,
    adapt_delta = 0.99
  )
  
  # save models
  tmp_model <- as_draws_df(samples$draws()) %>% select(
    alpha1,
    alpha2,
    alpha1_transformed,
    alpha2_transformed,
    alpha_diff,
    temperature,
    temperature_transformed
  )
  
  tmp_model$n_trial <- rep(n_trial, nrow(tmp_model))
  
  if (exists("recovery_df")){
    recovery_df <- rbind(recovery_df, tmp_model)
  } else {
    recovery_df <- tmp_model
  }
}
```

```{r}
# save data
# write_csv(recovery_df, "recovery.csv")
# load data
recovery_df <- read_csv("recovery.csv")
```

Plots
```{r}
ggplot(recovery_df) +
  geom_density(aes(alpha1_transformed), fill='blue', alpha=0.5) + 
  geom_density(aes(alpha2_transformed), fill='red', alpha=0.5) + 
  geom_vline(xintercept = 0.6, color='blue') + 
  geom_vline(xintercept = 0.8, color='red') +
  theme_bw() + facet_wrap(.~n_trial) + 
  labs(x='alpha', title='Estimation of alpha parameters by number of trials')
```

```{r}
ggplot(recovery_df) +
  geom_point(aes(n_trial, alpha_diff), alpha=0.5) +
  geom_line(aes(n_trial, y=0.2), color='red') +
  theme_bw()

ggplot(recovery_df, aes(as.factor(n_trial), alpha_diff)) +
  geom_violin(aes(as.factor(n_trial), alpha_diff)) +
  # stat_summary(aes(as.factor(n_trial), alpha_diff), fun=mean, geom="point", shape=23, size=2) +
  geom_boxplot(aes(as.factor(n_trial), alpha_diff), width=0.1) +
  geom_line(aes(as.factor(n_trial), y=0.2, group=1), color='red', linetype = "dashed") +
  theme_bw() + 
  labs(x="number of trials", y="difference in alpha", title="Difference in alpha between condition 1 and condition 2")
```

```{r}
ggplot(recovery_df, aes(as.factor(n_trial), temperature_transformed)) +
  geom_violin(aes(as.factor(n_trial), temperature_transformed)) +
  geom_boxplot(aes(as.factor(n_trial), temperature_transformed), width=0.1) +
  geom_line(aes(as.factor(n_trial), y=0.5, group=1), color='red', linetype = "dashed") +
  theme_bw() + 
  labs(x="number of trials", y="temperature", title="Estimation of temperature")
```


Summary statistics
```{r}
summary_stats <- recovery_df %>% 
  group_by(n_trial) %>% 
  summarise(across(everything(), list(mean = mean, Q1=~quantile(., probs = 0.25),
                    median=median, Q3=~quantile(., probs = 0.75))))

summary_stats %>% select(starts_with(c("n_tri", "alpha1_transf")))
summary_stats %>% select(starts_with(c("n_tri", "alpha2_transf")))
summary_stats %>% select(starts_with(c("n_tri","alpha_diff")))
summary_stats %>% select(starts_with(c("n_tri", "temperature_transf")))
```

## Producing iterated design
```{r}
# load model
file <- file.path('reinforcement_learning.stan')
mod <- cmdstan_model(file, cpp_options = list(stan_threads=TRUE))
print("Done compiling!")
```


```{r}
# we only need 2000 trials
d <- d %>% filter(trial <= 2500)

# make session variable
n_trial <- max(d$trial)
trials_in_session <- 100

d$session <- c(createSessions(n_trial, trials_in_session), createSessions(n_trial, trials_in_session))
n_session <- max(d$session)
d$trials_in_session <- rep(rep(1:trials_in_session, n_session), 2)

# initalize priors
alpha1_prior = c(0, 1)
alpha2_prior = c(0, 1)
temp_prior = c(0, 1)

# initialize df
session_df <- NULL

for (s in 1:n_session){
  
  print(paste("running session ", s, "of total", n_session))

  temp_d <- d %>% filter(session == s)
  
  # make data frames to make into matrices
  df_cond <- temp_d %>% mutate(cond = condition-1) %>% 
    subset(select=c(cond, condition, trials_in_session)) %>% 
    pivot_wider(names_from = condition, values_from = cond)
  
  df_choice <- temp_d %>% subset(select=c(choice, condition, trials_in_session)) %>% 
    pivot_wider(names_from = condition, values_from = choice)
  
  df_feedback <- temp_d %>% subset(select=c(feedback, condition, trials_in_session)) %>% 
    pivot_wider(names_from = condition, values_from = feedback)
  
  # data for the model
  data <- list(
    trials = max(temp_d$trials_in_session),
    cond = as.matrix(df_cond[,2:3]),
    choice = as.matrix(df_choice[,2:3]),
    feedback = as.matrix(df_feedback[,2:3]),
    alpha1_prior_values = alpha1_prior,
    alpha2_prior_values = alpha2_prior,
    temp_prior_values = temp_prior
  )
  
  # call stan
  samples <- mod$sample(
    data = data,
    seed = 123,
    chains = 2,
    parallel_chains = 2,
    threads_per_chain = 2,
    iter_warmup = 500,
    iter_sampling = 1000,
    refresh = 1000,
    max_treedepth = 20,
    adapt_delta = 0.99
  )
  
  # save models
  tmp_model <- as_draws_df(samples$draws()) %>% select(
    alpha1,
    alpha2,
    alpha1_transformed,
    alpha2_transformed,
    alpha_diff,
    temperature,
    temperature_transformed,
    alpha1_prior,
    alpha2_prior,
    temperature_prior
  )
  
  tmp_model$session <- rep(s, nrow(tmp_model))
  
  if (exists("session_df")){
    session_df <- rbind(session_df, tmp_model)
  } else {
    session_df <- tmp_model
  }
  
  # priors for next round
  alpha1_prior = c(mean(tmp_model$alpha1), sd(tmp_model$alpha1))
  alpha2_prior = c(mean(tmp_model$alpha2), sd(tmp_model$alpha2))
  temp_prior = c(mean(tmp_model$temperature), sd(tmp_model$temperature))
  
}

```

```{r}
# save df
write_csv(session_df, "session.csv")
# read df
session_df <- read_csv("session.csv")
```


```{r}
session_df %>% group_by(session) %>% 
  summarise(mean_alpha1 = mean(alpha1_transformed), 
            sd_alpha1 = sd(alpha1_transformed),
            mean_alpha2 = mean(alpha2_transformed),
            sd_alpha2 = sd(alpha2_transformed)
            )
```


```{r}
alpha1_update <- ggplot(session_df) +
  geom_density(aes(alpha1_transformed), fill='blue', alpha=0.5) + 
  geom_density(aes(alpha1_prior), fill='red', alpha=0.5) + 
  geom_vline(xintercept = 0.6, color='blue') +
  theme_bw() + facet_wrap(.~session) 

alpha2_update <- ggplot(session_df) +
  geom_density(aes(alpha2_transformed), fill='blue', alpha=0.5) + 
  geom_density(aes(alpha2_prior), fill='red', alpha=0.5) + 
  geom_vline(xintercept = 0.8, color='blue') +
  theme_bw() + facet_wrap(.~session)

alpha1_update
alpha2_update
```

```{r}
ggplot(session_df, aes(as.factor(session), alpha_diff)) +
  geom_violin(aes(as.factor(session), alpha_diff)) +
  geom_boxplot(aes(as.factor(session), alpha_diff), width=0.1) +
  geom_line(aes(as.factor(session), y=0.2, group=1), color='red', linetype = "dashed") +
  theme_bw() + 
  labs(x="session", y="difference in alpha", title="Difference in alpha between condition 1 and condition 2 over sessions")
```

